apiVersion: v1
kind: ConfigMap
metadata:
    name: mystaticweb-cm
data:
  nginx.conf: |
    server {
        listen          80;
        server_name     my-example.com;
        location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
        }
    }
